title: Alex Castro # your name (or website title) here
logo: "/images/AlexCastroimage-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Experienced Product, Program, and Operations manager providing visions to engineering teams while collaborating with Product, Sales, Operations, and Manufacturing! 
  Feel free to contact me via e-mail or LinkedIn if you feel my experience aligns with any of your open positions!
  <br><br>
  <b>e-mail: pmalexcastro@gmail.com</b>
  <br>
  <a href="https://www.linkedin.com/in/castro-alex-/">View My LinkedIn Profile</a>
  <br>
  <a href="https://drive.google.com/file/d/1v5CVKHLFjBhbTuE6hBt0j4bMQZHNbgE1/view?usp=sharing">View My Resume</a>
  <br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
